### ISSUE TITLE
Crashing while loading a mod on Neoforge (1.21.1)

### ISSUE THREAD

**Issue by TheNoirVoid** [Benjamin-Norton/AllTheTrims#42]
IDK what happened but I will send the crash report here.

[crash-2024-10-04_02.54.22-client.txt](https://github.com/user-attachments/files/17249443/crash-2024-10-04_02.54.22-client.txt)

**Comment by Bawnorton** [comment]
Fixed in 4.0.7, bug with newer version of neoforge

**Comment by TheNoirVoid** [comment]
I'm also using the newest version of Neoforge but it still crashes.

[crash-2024-10-04_03.18.00-client.txt](https://github.com/user-attachments/files/17249657/crash-2024-10-04_03.18.00-client.txt)

**Comment by Bawnorton** [comment]
Caused my illager invasion

**Comment by TheNoirVoid** [comment]
Hmmmm Can you make it compatible or I need to just choose to delete it?

**Comment by Bawnorton** [comment]
It's unrelated to all the trims. At least that's what the crash says.

**Comment by Bawnorton** [comment]
It's unrelated to all the trims. At least that's what the crash says.

**Comment by Bawnorton** [comment]
It's unrelated to all the trims. At least that's what the crash says.

**Comment by TheNoirVoid** [comment]
Okay. then anyway 
thanks for your work
